### ISSUE TITLE
@Composable invocations can only happen from the context of a @Composable function

### ISSUE THREAD

**Issue by breera** [Kaaveh/sdp-compose#1]
Hi Kaaveh! 
thanks for this library. I am facing an issue in this.
I want to set textsize in typography but i found error
**@Composable invocations can only happen from the context of a @Composable function**
Please provide a better way to use it in typography
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/34021979/193785473-3aaa956b-f844-4171-a9b6-e0cd0da277e3.png">

**Comment by Kaaveh** [comment]
You can use it like this:

```kotlin
/**
 * TextSmall
 */

val TextSmall: TextStyle
    @Composable get() =
        TextStyle(
            fontFamily = yekanRegularFont,
            fontSize = 12.ssp,
        )

val TextSmall_Medium: TextStyle
    @Composable get() =
        TextSmall.copy(
            fontFamily = yekanMediumFont,
        )

val TextSmall_Bold: TextStyle
    @Composable get() =
        TextSmall.copy(
            fontFamily = yekanBoldFont,
        )

val TextSmall_Secondary: TextStyle
    @Composable get() =
        TextSmall.copy(
            color = N500,
        )
```

**Comment by breera** [comment]
My question was how to use it in typography. The issue remains same if i set **TextSmall** in Typography

**Comment by Kaaveh** [comment]
@breera 
Use it like this:

```kotlin
val Typography: Typography
    @Composable get() = Typography(
        body1 = TextSmall
    )
```

With `@Composable` before every `get` variable method, you can access `sdp`

**Comment by srseibs** [comment]
```
val Typography: Typography
    @Composable get() = Typography(
        body1 = TextSmall
    )
```

Sorry it is still unclear how to apply this to a single Typography object -- can you show an example with more than one style?
