### ISSUE TITLE
Support for double values

### ISSUE THREAD

**Issue by dakshbhatt21** [Kaaveh/sdp-compose#2]
Currently, this library only works with integers.

Are there any plans for adding support to double?

<img width="353" alt="Screenshot 2024-01-07 at 11 46 02" src="https://github.com/Kaaveh/sdp-compose/assets/65546828/00a377fa-4c30-4459-a2b3-3b38fdaf4a2d">

**Comment by Kaaveh** [comment]
Unfortunately not, specially because this library just a wrapper around sdp.
